# Generated by Django 3.1.3 on 2020-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_date', models.DateTimeField()),
                ('blog_text', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
